### REINVENT4 TOML input ###
### Reinforcement Learning (RL) Run Mode ###

# General Options
run_type = "staged_learning"
use_cuda = true
tb_logdir = "TensorBoard_RL"
json_out_config = "RL_input.json"

[parameters]
# RL Parameters
summary_csv_prefix = "summary_RL"
use_checkpoint = false
batch_size = 128
unique_sequences = true
randomize_smiles = true

# Reinvent Molecule Generator
prior_file = "reinvent.prior"
agent_file = "reinvent.prior"

# Learning Strategy Parameters
[learning_strategy]
type = "dap"
sigma = 128
rate = 0.0001

# Stage Parameters
[[stage]]
chkpt_file = "RL_calc.chkpt"
termination = "simple"
max_score = 0.60
min_steps = 10
max_steps = 100

# Scoring Components Parameters
[scoring]
type = "geometric_mean"
parallel = false

