### REINVENT4 TOML input ###
### Scoring Run Mode ###

# General Input
run_type = "scoring"
use_cuda = true
json_out_config = "Scoring_input.json"

# Parameters for Calculation
[parameters]
smiles_file = "to_score.smi"
output_csv = "scored.csv"

# Scoring Components Parameters
[scoring]
type = "geometric_mean"
parallel = false

