### REINVENT4 TOML input ###
### Staged Learning (SL) Run Mode ###

# General Options
run_type = "staged_learning"
use_cuda = true
tb_logdir = "TensorBoard_SL"
json_out_config = "SL_input.json"

[parameters]
# SL Parameters
summary_csv_prefix = "summary_SL"
use_checkpoint = false
batch_size = 128
unique_sequences = true
randomize_smiles = true

# Reinvent Molecule Generator
prior_file = "reinvent.prior"
agent_file = "reinvent.prior"

# Learning Strategy Parameters
[learning_strategy]
type = "dap"
sigma = 128
rate = 0.0001

# Stage Parameters (S1)
[[stage]]
chkpt_file = "SL_calc_S1.chkpt"
termination = "simple"
max_score = 0.60
min_steps = 10
max_steps = 100

# Scoring Components (S1)
[stage.scoring]
type = "geometric_mean"
parallel = false

# Stage Parameters (S2)
[[stage]]
chkpt_file = "SL_calc_S2.chkpt"
termination = "simple"
max_score = 0.60
min_steps = 10
max_steps = 100

# Scoring Components (S2)
[stage.scoring]
type = "geometric_mean"
parallel = false

