### REINVENT4 TOML input ###
### Transfer Learning (TL) Run Mode ###

# General Options
run_type = "transfer_learning"
use_cuda = true
tb_logdir = "TensoBoard_TL"
json_out_config = "TL_input.json"

[parameters]
# TL Parameters
num_epochs = 10
save_every_n_epochs = 5
batch_size = 128
num_refs = 50
sample_batch_size = 100

# Reinvent molecule generator
input_model_file = "reinvent.prior"
smiles_file = "input_molecules.smi"
output_model_file = "TL_Reinvent.model"
validation_smiles_file = "validation_molecules.smi"

